language: objective-c
osx_image: xcode7.3

# Install swiftenv for Swift version management
# See: https://github.com/kylef/swiftenv/blob/master/docs/integrations/travis-ci.md
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - bundle install

script:
  # Workaround for Simulator getting stuck
  # See: https://github.com/travis-ci/travis-ci/issues/3040#issuecomment-146700203
  - open -b com.apple.iphonesimulator
  - ./bin/build
  - ./bin/test
  - ./bin/integration_tests

after_success:
  - bundle exec slather coverage --coveralls --travis
